server:
  port: 8081
  # Enable response compression
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
spring:
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    url: jdbc:mysql://db_server/db_cms_new
    username: root
    password: "$%^YGR^&UHGT^&U"
  cache:
    type: redis
    redis:
      time-to-live: 5m
  redis:
    host: localhost
qiniu:
  cdnDomain: http://cdn.cms.xkenmon.cn
