[#ftl]
[#-- @implicitly included --]

[#macro cms_article_list size page orderBy order][/#macro]
[#macro cms_article id blob][/#macro]
[#macro cms_category id ][/#macro]
[#macro cms_category id ][/#macro]
[#macro cms_category_tree][/#macro]
[#macro cms_content_list categoryId page size order orderBy][/#macro]
[#macro cms_friend_link page size][/#macro]
[#macro cms_index_article][/#macro]
[#macro cms_index_category][/#macro]
[#macro cms_tag_list page size][/#macro]
[#macro cms_type_list cate_type article_type page size order orderBy][/#macro]
