server:
  port: 8080
  # Enable response compression
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
spring:
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    url: jdbc:mysql://db_server/db_cms_new
    username: root
    password: "$%^YGR^&UHGT^&U"
  cache:
    type: redis
    redis:
      time-to-live: 5m
  redis:
    host: localhost
  data:
    mongodb:
      database: logging
      host: localhost
#logging:
#  level:
#    io.swagger.models.parameters.AbstractSerializableParameter: error
##jwt配置
auth:
  jwtSecret: wtfwtfftwesfdsfds
  jwtExpirationInMs: 259200000
logging:
  config: classpath:logback-spring.xml
